#define SCREEN_WIDTH 256
#define SCREEN_HEIGHT 192
#define CHAR_SIZE 8
#define SCREEN_CHARS_WIDTH (SCREEN_WIDTH / CHAR_SIZE)
#define SCREEN_CHARS_HEIGHT (SCREEN_HEIGHT / CHAR_SIZE)
#define CHARS_PER_ROW (SCREEN_WIDTH / CHAR_SIZE)
#define CHARS_PER_COLUMN (SCREEN_HEIGHT / CHAR_SIZE)
