#define SCREEN_WIDTH 256
#define SCREEN_HEIGHT 192
#define CHAR_SIZE 8

#define SCREEN_CHARS_WIDTH (SCREEN_WIDTH / CHAR_SIZE)
#define SCREEN_CHARS_WIDTH_BASE_0 (SCREEN_WIDTH / CHAR_SIZE - 1)
#define SCREEN_CHARS_HEIGHT (SCREEN_HEIGHT / CHAR_SIZE)
#define SCREEN_CHARS_HEIGHT_BASE_0 (SCREEN_HEIGHT / CHAR_SIZE - 1)
